CREATE POLICY "userpaper" ON public.user_paper FOR
INSERT WITH CHECK (auth.uid() = user_id);
--   Super base的表
create table public."user_paper" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id UUID REFERENCES auth.users NOT NULL,
    paper_content character varying [] null,
    paper_reference character varying [] null,
    constraint userPaper_pkey primary key (id)
) tablespace pg_default;